filter_features: yes
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
output_directory: development
tech: transcriptomics
data_type: RSEM
date: 2025-04-09 07:17:27
id: 2B115951-3
