data_type: RSEM
filter_features: yes
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
output_directory: development
normalization: limma_voom
date: 2025-04-09 11:06:29
id: F4AF3A12-6
n_class_0_train_ancestry: 107
n_class_1_train_ancestry: 629
n_class_0_infer_ancestry: 16
n_class_1_infer_ancestry: 42
n_features: 11436
