# Input
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
data_type: RSEM
meta_variables:
  - subtype
  - subtype_pooled
  - age
# Output
output_directory: development_descriptive_model_building

