# Classification
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
# Input
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
# Output
output_directory: development
# Filtering
filter_features: True
tech: transcriptomics
data_type: RSEM
