# Classification
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
# Input
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
data_type: RSEM
covariate: age  
# Output
output_directory: output/development_limma_interactions_parametric
# Features
filter_features: True
normalization_method: limma_voom
# Visualization
visual_val: True

