# Reproducibility
seed: 1
# Classification
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
# Input
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
data_type: RSEM
# Output
output_directory: output/development_cross_ancestry_parametric
# Features
filter_features: True
normalization_method: voom_normalization
# Bootstrap
n_bootstraps: 10
# Visualization
visual_val: True
