seed: 42
data_type: RSEM
perplexity: 50
save_coordinates: yes
data_path: data/downloads/GEO/Population-specific Mutation Patterns in Breast Tumors
  from African American, European American, and Kenyan Patients/GSE225846_raw_RSEM.h5ad
tech: transcriptomics
explained_variables:
- type
- age_(at_surgery)
- race
- er_status
- pr
- her2
- stage
output_directory: development_descriptive_model_building
date: 2025-04-24 08:34:04
id: DFD9FED7-9
