seed: 42
data_type: RSEM
perplexity: 50
save_coordinates: yes
n_pcs: 20
visual_val: yes
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
meta_variables:
- subtype
- subtype_pooled
- age
output_directory: development_descriptive_model_building
date: 2025-04-30 10:31:28
id: 4AE8373C-7
n_features: 20338
