seed: 42
data_type: RSEM
perplexity: 50
save_coordinates: yes
n_pcs: 20
visual_val: yes
data_path: data/downloads/GEO/Population-specific Mutation Patterns in Breast Tumors
  from African American, European American, and Kenyan Patients/GSE225846_raw_RSEM.h5ad
tech: transcriptomics
meta_variables:
- type
- age_(at_surgery)
- race
- er_status
- pr
- her2
- stage
output_directory: development_descriptive_model_building
date: 2025-04-24 12:44:25
id: 85B782FC-8
n_features: 46419
