data_type: RSEM
covariate: age
normalization: yes
filter_features: yes
percentile: 25
n_pcs: 20
perplexity: 50
save_coordinates: no
visual_val: yes
logFC_thr: 1
class_0: Basal
class_1: non-Basal
output_column: subtype_pooled
train_ancestry: eur
infer_ancestry: admix
ancestry_column: genetic_ancestry
data_path: data/inputs/PanCanAtlas_BRCA_raw_RSEM_subtypeNAremoved.h5ad
tech: transcriptomics
output_directory: development_interactions
normalization_method: limma_voom
date: 2025-05-14 11:49:57
id: 945390A1-D
n_class_0_train_ancestry: 107
n_class_1_train_ancestry: 629
n_class_0_infer_ancestry: 16
n_class_1_infer_ancestry: 42
n_features: 11436
